// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5psyEB_gONRTXg6M434cYx9gnEjK0bKc',
    appId: '1:539338969927:web:35d368987dcfb0a9233262',
    messagingSenderId: '539338969927',
    projectId: 'shopexchange-df2ad',
    authDomain: 'shopexchange-df2ad.firebaseapp.com',
    databaseURL: 'https://shopexchange-df2ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopexchange-df2ad.firebasestorage.app',
    measurementId: 'G-KSLM9D1D5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFuA8B2qeMkNK88U8J6UhfnNUsfn7Dsbk',
    appId: '1:539338969927:android:762205a214303cf1233262',
    messagingSenderId: '539338969927',
    projectId: 'shopexchange-df2ad',
    databaseURL: 'https://shopexchange-df2ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopexchange-df2ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8w0J8WrPdYntS1-vAVcaKjb57NGAnMcc',
    appId: '1:539338969927:ios:f66dcedb04cceb6e233262',
    messagingSenderId: '539338969927',
    projectId: 'shopexchange-df2ad',
    databaseURL: 'https://shopexchange-df2ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopexchange-df2ad.firebasestorage.app',
    iosBundleId: 'com.example.hrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8w0J8WrPdYntS1-vAVcaKjb57NGAnMcc',
    appId: '1:539338969927:ios:f66dcedb04cceb6e233262',
    messagingSenderId: '539338969927',
    projectId: 'shopexchange-df2ad',
    databaseURL: 'https://shopexchange-df2ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopexchange-df2ad.firebasestorage.app',
    iosBundleId: 'com.example.hrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5psyEB_gONRTXg6M434cYx9gnEjK0bKc',
    appId: '1:539338969927:web:7dabfd77a7becc4b233262',
    messagingSenderId: '539338969927',
    projectId: 'shopexchange-df2ad',
    authDomain: 'shopexchange-df2ad.firebaseapp.com',
    databaseURL: 'https://shopexchange-df2ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopexchange-df2ad.firebasestorage.app',
    measurementId: 'G-STZ89F83K0',
  );
}
